// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Nothing special about it",
    "title": "Calendar server",
    "version": "1.0.0"
  },
  "paths": {
    "/create_event": {
      "post": {
        "summary": "Creates event",
        "parameters": [
          {
            "name": "event",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/event"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "created successfully"
          }
        }
      }
    }
  },
  "definitions": {
    "event": {
      "type": "object",
      "properties": {
        "description": {
          "type": "string"
        },
        "id": {
          "type": "string",
          "readOnly": true
        },
        "time_end": {
          "type": "string",
          "format": "date-time"
        },
        "time_start": {
          "type": "string",
          "format": "date-time"
        },
        "title": {
          "type": "string"
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Nothing special about it",
    "title": "Calendar server",
    "version": "1.0.0"
  },
  "paths": {
    "/create_event": {
      "post": {
        "summary": "Creates event",
        "parameters": [
          {
            "name": "event",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/event"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "created successfully"
          }
        }
      }
    }
  },
  "definitions": {
    "event": {
      "type": "object",
      "properties": {
        "description": {
          "type": "string"
        },
        "id": {
          "type": "string",
          "readOnly": true
        },
        "time_end": {
          "type": "string",
          "format": "date-time"
        },
        "time_start": {
          "type": "string",
          "format": "date-time"
        },
        "title": {
          "type": "string"
        }
      }
    }
  }
}`))
}
