// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/ntnbrtnkv/otus-golang/calendar/http/models"
)

// GetEventsForDayOKCode is the HTTP code returned for type GetEventsForDayOK
const GetEventsForDayOKCode int = 200

/*
GetEventsForDayOK List of events

swagger:response getEventsForDayOK
*/
type GetEventsForDayOK struct {

	/*
	  In: Body
	*/
	Payload *models.Events `json:"body,omitempty"`
}

// NewGetEventsForDayOK creates GetEventsForDayOK with default headers values
func NewGetEventsForDayOK() *GetEventsForDayOK {

	return &GetEventsForDayOK{}
}

// WithPayload adds the payload to the get events for day o k response
func (o *GetEventsForDayOK) WithPayload(payload *models.Events) *GetEventsForDayOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get events for day o k response
func (o *GetEventsForDayOK) SetPayload(payload *models.Events) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetEventsForDayOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
