// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/ntnbrtnkv/otus-golang/calendar/http/models"
)

// GetEventsForWeekOKCode is the HTTP code returned for type GetEventsForWeekOK
const GetEventsForWeekOKCode int = 200

/*
GetEventsForWeekOK List of events

swagger:response getEventsForWeekOK
*/
type GetEventsForWeekOK struct {

	/*
	  In: Body
	*/
	Payload *models.Events `json:"body,omitempty"`
}

// NewGetEventsForWeekOK creates GetEventsForWeekOK with default headers values
func NewGetEventsForWeekOK() *GetEventsForWeekOK {

	return &GetEventsForWeekOK{}
}

// WithPayload adds the payload to the get events for week o k response
func (o *GetEventsForWeekOK) WithPayload(payload *models.Events) *GetEventsForWeekOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get events for week o k response
func (o *GetEventsForWeekOK) SetPayload(payload *models.Events) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetEventsForWeekOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
