// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetEventsForWeekHandlerFunc turns a function with the right signature into a get events for week handler
type GetEventsForWeekHandlerFunc func(GetEventsForWeekParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetEventsForWeekHandlerFunc) Handle(params GetEventsForWeekParams) middleware.Responder {
	return fn(params)
}

// GetEventsForWeekHandler interface for that can handle valid get events for week params
type GetEventsForWeekHandler interface {
	Handle(GetEventsForWeekParams) middleware.Responder
}

// NewGetEventsForWeek creates a new http.Handler for the get events for week operation
func NewGetEventsForWeek(ctx *middleware.Context, handler GetEventsForWeekHandler) *GetEventsForWeek {
	return &GetEventsForWeek{Context: ctx, Handler: handler}
}

/*
	GetEventsForWeek swagger:route GET /events_for_week getEventsForWeek

Show events for week
*/
type GetEventsForWeek struct {
	Context *middleware.Context
	Handler GetEventsForWeekHandler
}

func (o *GetEventsForWeek) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetEventsForWeekParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
