// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetEventsForDayHandlerFunc turns a function with the right signature into a get events for day handler
type GetEventsForDayHandlerFunc func(GetEventsForDayParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetEventsForDayHandlerFunc) Handle(params GetEventsForDayParams) middleware.Responder {
	return fn(params)
}

// GetEventsForDayHandler interface for that can handle valid get events for day params
type GetEventsForDayHandler interface {
	Handle(GetEventsForDayParams) middleware.Responder
}

// NewGetEventsForDay creates a new http.Handler for the get events for day operation
func NewGetEventsForDay(ctx *middleware.Context, handler GetEventsForDayHandler) *GetEventsForDay {
	return &GetEventsForDay{Context: ctx, Handler: handler}
}

/*
	GetEventsForDay swagger:route GET /events_for_day getEventsForDay

Show events for day
*/
type GetEventsForDay struct {
	Context *middleware.Context
	Handler GetEventsForDayHandler
}

func (o *GetEventsForDay) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetEventsForDayParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
