// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// NewGetEventsForMonthParams creates a new GetEventsForMonthParams object
//
// There are no default values defined in the spec.
func NewGetEventsForMonthParams() GetEventsForMonthParams {

	return GetEventsForMonthParams{}
}

// GetEventsForMonthParams contains all the bound params for the get events for month operation
// typically these are obtained from a http.Request
//
// swagger:parameters GetEventsForMonth
type GetEventsForMonthParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  Required: true
	  In: query
	*/
	Month strfmt.Date
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetEventsForMonthParams() beforehand.
func (o *GetEventsForMonthParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	qMonth, qhkMonth, _ := qs.GetOK("month")
	if err := o.bindMonth(qMonth, qhkMonth, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindMonth binds and validates parameter Month from query.
func (o *GetEventsForMonthParams) bindMonth(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("month", "query", rawData)
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// AllowEmptyValue: false

	if err := validate.RequiredString("month", "query", raw); err != nil {
		return err
	}

	// Format: date
	value, err := formats.Parse("date", raw)
	if err != nil {
		return errors.InvalidType("month", "query", "strfmt.Date", raw)
	}
	o.Month = *(value.(*strfmt.Date))

	if err := o.validateMonth(formats); err != nil {
		return err
	}

	return nil
}

// validateMonth carries on validations for parameter Month
func (o *GetEventsForMonthParams) validateMonth(formats strfmt.Registry) error {

	if err := validate.FormatOf("month", "query", "date", o.Month.String(), formats); err != nil {
		return err
	}
	return nil
}
