// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PostUpdateEventHandlerFunc turns a function with the right signature into a post update event handler
type PostUpdateEventHandlerFunc func(PostUpdateEventParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostUpdateEventHandlerFunc) Handle(params PostUpdateEventParams) middleware.Responder {
	return fn(params)
}

// PostUpdateEventHandler interface for that can handle valid post update event params
type PostUpdateEventHandler interface {
	Handle(PostUpdateEventParams) middleware.Responder
}

// NewPostUpdateEvent creates a new http.Handler for the post update event operation
func NewPostUpdateEvent(ctx *middleware.Context, handler PostUpdateEventHandler) *PostUpdateEvent {
	return &PostUpdateEvent{Context: ctx, Handler: handler}
}

/*
	PostUpdateEvent swagger:route POST /update_event postUpdateEvent

Update event
*/
type PostUpdateEvent struct {
	Context *middleware.Context
	Handler PostUpdateEventHandler
}

func (o *PostUpdateEvent) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostUpdateEventParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
