consumes:
  - application/x-www-form-urlencoded
info:
  description: Nothing special about it
  title: Calendar server
  version: 1.0.0

produces:
  - application/json
schemes:
  - http
host: localhost:1234
swagger: "2.0"

parameters:
  eventID:
    name: id
    in: formData
    type: string
    required: true
  eventTitle:
    name: title
    in: formData
    type: string
    required: true
  eventDescription:
    name: description
    in: formData
    type: string
    required: true
  eventStart:
    name: time_start
    in: formData
    type: string
    format: date-time
    required: true
  eventEnd:
    name: time_end
    in: formData
    type: string
    format: date-time
    required: true

definitions:
  event:
    type: object
    required:
      - title
      - description
      - time_end
      - time_start
    properties:
      id:
        type: string
        readOnly: true
      title:
        type: string
      description:
        type: string
      time_start:
        type: string
        format: date-time
      time_end:
        type: string
        format: date-time
  events:
    type: object
    properties:
      result:
        type: array
        items:
          $ref: '#/definitions/event'
  error:
    type: object
    properties:
      error:
        type: string

paths:
  /create_event:
    post:
      parameters:
        - $ref: "#/parameters/eventTitle"
        - $ref: "#/parameters/eventDescription"
        - $ref: "#/parameters/eventStart"
        - $ref: "#/parameters/eventEnd"
      summary: Creates event
      responses:
        '201':
          description: Created successfully
        '400':
          description: Failed to create event
          schema:
            $ref: '#/definitions/error'
  /update_event:
    post:
      parameters:
        - $ref: "#/parameters/eventID"
        - $ref: "#/parameters/eventTitle"
        - $ref: "#/parameters/eventDescription"
        - $ref: "#/parameters/eventStart"
        - $ref: "#/parameters/eventEnd"
      summary: Update event
      responses:
        '200':
          description: Updated successfully
        '400':
          description: Failed to update event
          schema:
            $ref: '#/definitions/error'
  /delete_event:
    post:
      parameters:
        - $ref: "#/parameters/eventID"
      summary: Delete event
      responses:
        '200':
          description: Deleted successfully
        '400':
          description: Failed to delete event
          schema:
            $ref: '#/definitions/error'
  /events_for_day:
    get:
      summary: Show events for day
      parameters:
        - name: day
          in: query
          type: string
          format: date
          required: true
      responses:
        '200':
          description: List of events
          schema:
            $ref: '#/definitions/events'
  /events_for_week:
    get:
      summary: Show events for week
      parameters:
        - name: week
          in: query
          type: string
          format: date
          required: true
      responses:
        '200':
          description: List of events
          schema:
            $ref: '#/definitions/events'
  /events_for_month:
    get:
      summary: Show events for month
      parameters:
        - name: month
          in: query
          type: string
          format: date
          required: true
      responses:
        '200':
          description: List of events
          schema:
            $ref: '#/definitions/events'